# Generated by Django 2.2 on 2020-06-06 18:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEvent',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%h/', verbose_name='Заставка')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент')),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Краткое описание')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('data_modifed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('data_event', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность мероприятия')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цены')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%h/', verbose_name='Заставка')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент')),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Краткое описание')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('data_modifed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность мероприятия')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
