# Generated by Django 2.2 on 2020-07-02 01:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEvent',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%h/', verbose_name='Заставка')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент')),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Краткое описание')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('data_modifed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('data_event', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность мероприятия')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цены')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.CategoryEvent', verbose_name='Категория')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Teachers', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='UserInEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплатил ли пользователь участие')),
                ('active', models.BooleanField(default=True, verbose_name='Будет ли принимать участие пользователь')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации на мероприятие')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь, принимающий участие в мероприятии',
                'verbose_name_plural': 'Пользователи, принимающие участие в мероприятиях',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%h/', verbose_name='Заставка')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент')),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Краткое описание')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('data_modifed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность мероприятия')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Teachers', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
