# Generated by Django 2.2 on 2020-07-02 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='data_modifed',
        ),
        migrations.RemoveField(
            model_name='news',
            name='data_modifed',
        ),
        migrations.AlterField(
            model_name='event',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
