# Generated by Django 2.2 on 2020-07-02 15:53

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='URL-страницы', max_length=200, verbose_name='Ссылка')),
                ('video', embed_video.fields.EmbedVideoField(help_text='Заходим на страницу видео-Поделиться-Встроить-Копируем link, содержащий строку embeded', verbose_name='Загрузить видео')),
                ('data_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания отзыва')),
            ],
            options={
                'verbose_name': 'Видеоотзыв',
                'verbose_name_plural': 'Видеоотзывы',
            },
        ),
    ]
