# Generated by Django 2.2 on 2020-06-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_event',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%h/', verbose_name='Заставка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%h/', verbose_name='Заставка'),
        ),
    ]
