# Generated by Django 2.2 on 2020-06-08 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_auto_20200606_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплатил ли пользователь участие')),
                ('active', models.BooleanField(default=True, verbose_name='Будет ли принимать участие пользователь')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации на мероприятие')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь, принимающий участие в мероприятии',
                'verbose_name_plural': 'Пользователи, принимающие участие в мероприятиях',
            },
        ),
    ]
