# Generated by Django 2.2 on 2020-07-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' класс', max_length=8, verbose_name='Номер класса')),
            ],
            options={
                'verbose_name': 'Номер класса',
                'verbose_name_plural': 'Номера классов',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткая информация')),
                ('full_info', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Полная информация')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures/teachers/', verbose_name='Фото преподавателя')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('telephone_number', models.CharField(max_length=12, verbose_name='Телефонный номер')),
                ('name_school', models.CharField(max_length=50, verbose_name='Название школы')),
                ('date_birthday', models.DateField(verbose_name='День рождения')),
                ('is_parent', models.BooleanField(blank=True, default=False, null=True, verbose_name='Родитель')),
                ('children_telephone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефонный номер')),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ClassNumber', verbose_name='Номер класса')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
